services:
  db1:
    image: mysql:9.1
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    volumes:
      - ./db1-init.sql:/docker-entrypoint-initdb.d/init.sql
  db2:
    image: postgres:17.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - 5432:5432
    volumes:
      - ./db2-init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB1_HOST: db1
      DB2_HOST: db2
    depends_on:
      - db1
      - db2
    ports:
      - 8080:8080